openai.api.endpoint=https://virtual-avatar-gpt.openai.azure.com
openai.api.key=01b8dddc9d564d5c92edd909af2227e5
openai.api.version=2024-05-01-preview
openai.vector_store=vs_iRFcdxoigsQgtgasBgCUWtq5
openai.key=ae603684648445fe343ba354f0d3eefa02ff3ba6c8e359bafeb375bc93afdb20"