# Compatibility + Warning Fixes

import multiprocessing
multiprocessing.set_start_method("fork", force=True)

import os

os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"
os.environ["TOKENIZERS_PARALLELISM"] = "false"
os.environ["LC_ALL"] = "en_US.UTF-8"
os.environ["LANG"] = "en_US.UTF-8"
os.environ["OMP_NUM_THREADS"] = "1"

# Core Imports

from setfit import SetFitModel, Trainer, TrainingArguments
from datasets import Dataset

# Step 1: Training data

texts = [

    # Transaction History

    "Show me what I spent recently",
    "Need to check my money trail",
    "Pull up my past transactions",
    "Can I see where my cash went?",
    "What's my recent spending like?",
    "How much I spent last week?",
    "What was the damage to my wallet?",
    "Give me my expense report",
    "Track my spending for last few days",
    "What did I pay for yesterday?",
    "My transaction log please",
    "Spending rundown please",
    "Show recent activity on my account",
    "What's my money movement like?",
    "Yo, what I blow my cash on?",
    "Peep my spendings this week",
    "Where did my dollars go?",
    "What was I splurging on lately?",
    "Give me a list of my buys",
    "Damage control - check my spend",
    "How much I blew over the weekend?",
    "Can you flex my last few payments?",
    "Last few purchases - show me",
    "What have I been spending on?",
    "Breakdown of my wallet leakage",
    "Expenses for the last few days?",
    "My financial activity pls",
    "Can I see what I paid for recently?",
    "How did I burn my wallet?",
    "What's my recent wallet trauma?",
    "How much went out last week?",
    "Pull up my weekly damage",
    "Spending receipts please",
    "My outgoing money report",
    "Where my coins went sia?",
    "Yo how much I splashed this week?",
    "Check what I spent over the past days",
    "Expenditure report pls",
    "Give me transaction history ah",
    "Can see what I spent yesterday?",
    "Peep my last week's spending vibes",
    "Money gone where bro?",
    "How I spent my money recently?",
    "What was my last transaction?",
    "Any purchases last 3 days?",
    "Can u show how much I used lately?",
    "Show my expense flow pls",
    "Wanna see my financial footprint",
    "How did my cash disappear?",
    "Track my shopping damage",


    # Check Balance
    "How much do I have left?",
    "Lemme see my balance real quick",
    "Check account balance please",
    "Am I broke or nah",
    "Show me my funds",
    "What's my current bank balance?",
    "How stacked am I right now?",
    "Can I see my account total?",
    "Balance check please",
    "Wallet status check pls",
    "Do I still got money?",
    "Show current funds",
    "Check how much is left inside",
    "How much money still got?",
    "Yo can I still afford bubble tea?",
    "Update me on my account balance",
    "Can you display my bank funds?",
    "Any money left in my bank?",
    "Am I cash poor right now?",
    "How many dollars left inside?",
    "Pls check wallet funds",
    "How loaded is my account?",
    "What's my balance now?",
    "Give me my remaining funds",
    "How much I got left inside?",
    "Is there anything left in the account?",
    "Bank still got vibes?",
    "Account got enough for lunch?",
    "Money situation pls",
    "Cash got how much left?",
    "How broke am I?",
    "Bank vibes check",
    "Check my bank amount",
    "Still got moolah?",
    "Can still withdraw or not?",
    "Balance update pls",
    "How many bucks left?",
    "Is my account still breathing?",
    "Account balance now please",
    "Show me remaining balance",
    "Can I see my available funds?",
    "Is my wallet dead?",
    "Funds check pls",
    "My balance now",
    "Is there cash still?",
    "Give me cash left details",
    "Any cash left in there?",
    "Pls show my wallet status",
    "I need to see my balance ah",
    "Tell me how broke I am",

    # Logout
    "I'm done, log me out",
    "Time to bounce, sign me out",
    "Can you log me off?",
    "Exit the app please",
    "I wanna logout now",
    "Log me out, thanks",
    "I'm bouncing off, log me out",
    "Sign me out now please",
    "I'm out, logout time",
    "Get me outta here",
    "I'm ghosting, log me off",
    "Time to dip, log me out",
    "Logging off now",
    "I'm logging out",
    "Bye app, log me off",
    "Peace out, log me out",
    "Signing off now",
    "I'm done for the day, log me out",
    "I'm clocking off, log out pls",
    "I'm done with banking for now, logout",
    "Kill the session",
    "End my session now",
    "I'm out of here, log me off",
    "Closing time, log me off",
    "Let me out of this app",
    "I need to logout now",
    "Exit me from the app",
    "Bye bye bank app",
    "Close this for me",
    "Time to go offline",
    "I wanna bounce now",
    "Switching off, logout pls",
    "Clock me out please",
    "End my online session",
    "Shut this down for me",
    "I wanna log off already",
    "Wrap this up, sign me out",
    "Deactivate the app session",
    "I'm stepping away, logout pls",
    "End session",
    "Kick me out of here",
    "Logging out now bro",
    "Shut down my banking session",
    "Turn off my login",
    "Unplug me",
    "Exit me out now",
    "Bounce me from this app",
    "Time to ghost",
    "Gonna dip now, sign out",
    "Off I go, log me off",


    # Money Lock
    "Lock my money right now",
    "Secure $100 for me",
    "Freeze my account funds",
    "Put $50 into lock mode",
    "Stash $200 away",
    "Hide my cash",
    "Lock up my balance",
    "Protect my savings",
    "Hold this money for me",
    "Activate money lock",
    "Yeet my cash into safety mode",
    "Don't let me touch $30",
    "Put $100 in a vault or something",
    "Don't let me blow this money",
    "I need to lock up some funds ASAP",
    "Throw my money in a safe zone",
    "Put it on financial timeout",
    "Keep $20 out of my hands",
    "Freeze that dough",
    "Chill my funds please",
    "Keep this money safe",
    "Don't let me use this amount",
    "Put this money somewhere I can't spend",
    "Secure this chunk of cash",
    "Temporarily lock these funds",
    "Quarantine my savings",
    "Make sure I can't touch this money",
    "Turn on spending lock",
    "Money vault mode on",
    "Add this to a locked stash",
    "Guard this $75",
    "Make this money untouchable",
    "Stash away $40 quietly",
    "Vault mode please",
    "Throw this into lockdown",
    "Help me not touch this amount",
    "Turn on protection for $60",
    "Lock this down",
    "No spending allowed for this",
    "Shield this amount",
    "Engage lock mode",
    "Transfer to lock zone",
    "Hide $25 from myself",
    "Put $10 where I can't reach",
    "Turn on save lock",
    "Lock this before I waste it",
    "Save this but don't let me access it",
    "Lock these funds",
    "Enable fund lock now",
    "Activate protection for this money",



    # Generic
    "Hey there",
    "What's up?",
    "Yo",
    "How's your day going?",
    "Tell me something cool",
    "Do you like cats?",
    "I'm bored",
    "What's your vibe?",
    "How are you today?",
    "Hello?",
    "What's the meaning of life?",
    "Are you a bot?",
    "Tell me a joke",
    "How old are you?",
    "What's your name?",
    "Are you alive?",
    "Talk to me",
    "What do you do?",
    "Say something funny",
    "I'm just testing",
    "Show me something random",
    "Good morning",
    "Do you like memes?",
    "I'm confused",
    "Can I ask you something?",
    "Who built you?",
    "Tell me a secret",
    "Why are you here?",
    "Banana",
    "What's your favorite color?",
    "Do you sleep?",
    "How smart are you?",
    "What should I eat?",
    "What's trending now?",
    "Any movie recommendations?",
    "Play a song",
    "Recommend something",
    "Are you real?",
    "Can I vibe with you?",
    "What's going on?",
    "Why is the sky blue?",
    "Do you have emotions?",
    "What's happening?",
    "Teach me something",
    "Say hi",
    "Do you dream?",
    "What are we doing?",
    "What's new?",
    "Do you have a soul?",
    "Tell me about yourself",


    # Deals
    "Got any promos?",
    "Show me the latest deals",
    "Any cashback offers now?",
    "Where the good promos at?",
    "Hit me with some banking deals",
    "What promos are live?",
    "Give me offers please",
    "List your current promotions",
    "Anything on discount?",
    "Show me savings promos",
    "Deals of the week?",
    "Drop the hot promos",
    "Got any special offers?",
    "Best deals right now?",
    "Where's the sale stuff?",
    "Send me those banking deals",
    "Any exclusive promotions?",
    "Tell me about your promos",
    "What's the hottest promo now?",
    "Promo time?",
    "Slide me the top deals",
    "Any offers I can use?",
    "Is there a flash deal?",
    "Deals and discounts pls",
    "What's the best discount available?",
    "Hook me up with a deal",
    "Anything on sale now?",
    "Got any rebates?",
    "Give me some offers for today",
    "Cashback promos?",
    "Current banking deals?",
    "Any good offers?",
    "Lowkey looking for promos",
    "Which cards have promos now?",
    "What promotions you got?",
    "Deals I can use right now?",
    "Slide me some juicy offers",
    "What can I save on today?",
    "Send me deal notifications",
    "Today's top promo?",
    "What promos are trending?",
    "Bank deals rn?",
    "I want to see the promotions",
    "Promo roundup?",
    "Show all your deals",
    "Where can I get discount perks?",
    "Are there credit card offers?",
    "Got exclusive perks?",
    "Let me browse offers",
    "Show me how to save",


 # Referrals
    "Refer a friend",
    "Invite my friends",
    "Can I refer someone?",
    "Hook up my buddy",
    "Share the app with my friend",
    "Send referral link",
    "How do I refer someone?",
    "Refer my contacts",
    "Give me my referral code",
    "Invite and earn",
    "Get rewards for referrals?",
    "Refer to get bonus",
    "What's the referral program?",
    "Tell me about refer and earn",
    "Any referral bonuses?",
    "Send friend invite",
    "Want to refer a pal",
    "Bring a friend deal?",
    "Refer and get rewarded",
    "Let me refer someone",
    "Drop that referral link",
    "Help me invite a friend",
    "Earn by inviting",
    "Friend referral system?",
    "Is there a referral offer?",
    "Send my invite code",
    "How to refer others?",
    "Where's my referral reward?",
    "Refer more to earn more",
    "Show my invite link",
    "Can I earn by referring?",
    "Get rewarded for invites?",
    "Refer contacts for benefits",
    "Friend invite promo?",
    "What's my referral link?",
    "Refer now",
    "Hook me up with referral perks",
    "Get referral incentives",
    "Share invite",
    "Friend reward program?",
    "Want to refer now",
    "Send a referral",
    "Refer someone today",
    "Can I invite people?",
    "Where's the referral dashboard?",
    "Any friend reward deals?",
    "Invite a friend and win",
    "Tell me how to refer",
    "Bring friends and get rewarded",
    "Referral please",
]

labels = (
    ["transaction_history"] * 50 +
    ["check_balance"] * 50 +
    ["logout"] * 50 +
    ["money_lock"] * 50 +
    ["generic"] * 50 +
    ["deals"] * 50 +
    ["refer_a_friend"] * 50
)


train_data = Dataset.from_dict({
    "text": texts,
    "label": labels
})

# Step 2: Define labels
unique_labels = sorted(list(set(labels)))

# Step 3: Load Model

model = SetFitModel.from_pretrained(
    "BAAI/bge-small-en-v1.5",
    labels=unique_labels
)

# Step 4: Training Args

args = TrainingArguments(
    batch_size=8,
    num_epochs=10,
)

# Step 5: Train Model

trainer = Trainer(
    model=model,
    args=args,
    train_dataset=train_data,
)
trainer.train()

# Step 6: Save Model

model.save_pretrained("setfit_model")
print(" Model trained and saved at ./setfit_model")

